### ISSUE TITLE
Function "from reus.fotmob import fm_match_data" stat player "none"

### ISSUE THREAD

**Issue by Gyracat** [ian-shepherd/reus_data#2]
from reus.fotmob import fm_match_data

and test run 

# Import the fm_match_data function
from reus.fotmob import fm_match_data

# Fetch match data for the given match ID
actual = fm_match_data("3901251")

Stat by player show "none" example xG ,Goal etc.

![image](https://github.com/ian-shepherd/reus_data/assets/79399115/03628971-3632-4c13-9a90-19eeae63bc13)

**Comment by ian-shepherd** [comment]
I have a current fix I am testing that will solve this issue and will be deployed by next week. I forgot to push my changes to my development branch and am away from my computer for next few days so unable to finish until I can get back home. The source of the issue is an underlying change fotmob made on their backend. Apologies for the delay.

**Comment by Gyracat** [comment]
Thank you ❤️

**Comment by ian-shepherd** [comment]
this issue should be solved in either versions 1.1.5 or 1.1.6. Both are the exact same, I just made a mistake in writing the python version in the setup file that prevented install in python 3.10 so 1.1.6 is the more "correct" one to use
